module.exports =
    BTS_BLOCKCHAIN_MIN_NAME_SIZE: 1
    BTS_BLOCKCHAIN_MAX_NAME_SIZE: 63
    BTS_BLOCKCHAIN_MAX_NAME_DATA_SIZE: (1024*64)
    BTS_BLOCKCHAIN_MAX_MEMO_SIZE: 19 # bytes
    BTS_BLOCKCHAIN_MAX_SYMBOL_SIZE: 8 # characters
    BTS_BLOCKCHAIN_MIN_SYMBOL_SIZE: 3 # characters