exports = 
    BTS_WALLET_VERSION: 109

    BTS_WALLET_MIN_PASSWORD_LENGTH: 8
    BTS_WALLET_MIN_BRAINKEY_LENGTH: 32
    
    BTS_WALLET_DEFAULT_UNLOCK_TIME_SEC: (60*60)
    
    BTS_WALLET_DEFAULT_TRANSACTION_FEE: 50000 # XTS
    
    BTS_WALLET_DEFAULT_TRANSACTION_EXPIRATION_SEC: 360