
watchify = require('watchify')
fs = require('fs')
path = require('path')
fromArgs = require('watchify/bin/args')
w = fromArgs(process.argv.slice(2))

bundle = ->
  wb = w.bundle()
  wb.on 'error', (err) ->
    console.error String(err)
    fs.writeFile outfile, 'console.error(' + JSON.stringify(String(err)) + ')', (err) ->
      if err
        console.error err
      return
    return
  wb.pipe fs.createWriteStream(dotfile)
  bytes = undefined
  time = undefined
  w.on 'bytes', (b) ->
    bytes = b
    return
  w.on 'time', (t) ->
    time = t
    return
  wb.on 'end', ->
    fs.rename dotfile, outfile, (err) ->
      if err
        return console.error(err)
      if verbose
        console.error bytes + ' bytes written to ' + outfile + ' (' + (time / 1000).toFixed(2) + ' seconds)'
      return
    return
  return

w.setMaxListeners Infinity
outfile = w.argv.o or w.argv.outfile
verbose = w.argv.v or w.argv.verbose
if !outfile
  console.error 'You MUST specify an outfile with -o.'
  process.exit 1
# https://github.com/substack/watchify/issues/140
dotfile = '.' + path.basename(outfile)
w.on 'update', bundle
bundle()

# ---
# generated by js2coffee 2.0.1
